# paths relative to project root
path: ../data/raw
train: train/images
val: val/images
test: test/images

# 3 classes for VISTA-S detection
nc: 3
names: ['fire_extinguisher', 'oxygen_tank', 'toolbox']